export const responseData = [
    {
        menuId: 23,
        parentId: 0,
        displayOrder: 1,
        type: "Image",
        item: "HOME",
        script: "/",
        condition: "home-condition",
        description: "this is simple home",
        recordStatus: "Active",
        children: [],
    },
    {
        menuId: 161,
        parentId: 0,
        displayOrder: 2,
        type: "Text",
        item: "TRAVEL",
        script: "/modules/travel",
        condition: "TRAVEL",
        description: "TRAVEL",
        recordStatus: "Active",
        children: [],
    },
    {
        menuId: 162,
        parentId: 0,
        displayOrder: 3,
        type: "Image",
        item: "HELP",
        script: "help",
        condition: "Help",
        description: "Help",
        recordStatus: "Active",
        children: [],
    },
    {
        menuId: 160,
        parentId: 0,
        displayOrder: 4,
        type: "Text",
        item: "ADMIN",
        script: "/admin",
        condition: "Admin-Condition",
        description: "This is admin",
        recordStatus: "Active",
        children: [
            {
                menuId: 24,
                parentId: 160,
                displayOrder: 1,
                type: "Image",
                item: "Configuration",
                script: "about",
                condition: "About-condition",
                description: "Configuration Menu",
                recordStatus: "Active",
                children: [
                    {
                        menuId: 29,
                        parentId: 24,
                        displayOrder: 1,
                        type: "Text",
                        item: "Company",
                        script: "/modules/company",
                        condition: "Child2-condition",
                        description: "Company",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 30,
                        parentId: 24,
                        displayOrder: 2,
                        type: "Text",
                        item: "Person",
                        script: "/modules/person",
                        condition: "Shown",
                        description: "Person Meniu",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 31,
                        parentId: 24,
                        displayOrder: 3,
                        type: "Text",
                        item: "User",
                        script: "/modules/users",
                        condition: "Child34-condition",
                        description: "User menu",
                        recordStatus: "Active",
                        children: [],
                    },
                ],
            },
            {
                menuId: 174,
                parentId: 160,
                displayOrder: 2,
                type: "Text",
                item: "Application Forms",
                script: "/modules/application",
                condition: "Help-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 26,
                parentId: 160,
                displayOrder: 3,
                type: "Image",
                item: "Reports",
                script: "logs",
                condition: "Menu4-condition",
                description: "Logs Menu",
                recordStatus: "Active",
                children: [
                    {
                        menuId: 33,
                        parentId: 26,
                        displayOrder: 1,
                        type: "Text",
                        item: "Session",
                        script: "/logs/session",
                        condition: "logs-session",
                        description: "Logs Menu",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 34,
                        parentId: 26,
                        displayOrder: 2,
                        type: "Text",
                        item: "Activity",
                        script: "/logs/activity",
                        condition: "Logs-Activity",
                        description: "Activity Logs",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 35,
                        parentId: 26,
                        displayOrder: 3,
                        type: "Text",
                        item: "Audit",
                        script: "/logs/audit",
                        condition: "Logs-Audit",
                        description: "Audit Menu",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 36,
                        parentId: 26,
                        displayOrder: 4,
                        type: "Text",
                        item: "Error",
                        script: "/logs/error",
                        condition: "Logs-Error",
                        description: "Error API",
                        recordStatus: "Active",
                        children: [],
                    },
                ],
            },
            {
                menuId: 165,
                parentId: 160,
                displayOrder: 4,
                type: "Text",
                item: "IP Address Book",
                script: "/modules/ip_address_book",
                condition: "NONE",
                description: "IP Address Book",
                recordStatus: "Undeleted",
                children: [],
            },
            {
                menuId: 168,
                parentId: 160,
                displayOrder: 5,
                type: "Text",
                item: "Exchange Rates",
                script: "/modules/exchangeRate",
                condition: "0",
                description: null,
                recordStatus: "Active",
                children: [],
            },
        ],
    },
    {
        menuId: 194,
        parentId: 0,
        displayOrder: 5,
        type: "Text",
        item: "SYSTEM",
        script: "dummy",
        condition: "true",
        description: 'All data concerning the system "Appnox"',
        recordStatus: "Active",
        children: [
            {
                menuId: 164,
                parentId: 194,
                displayOrder: 1,
                type: "Text",
                item: "Activity Types",
                script: "/modules/activity_type",
                condition: "None",
                description: "Activity Types",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 192,
                parentId: 194,
                displayOrder: 2,
                type: "Text",
                item: "Fees",
                script: "/modules/fees",
                condition: "Admin-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 186,
                parentId: 194,
                displayOrder: 3,
                type: "Text",
                item: "Knowledge Base",
                script: "/modules/knowledgeBase",
                condition: "None",
                description: "Knowledge base Module",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 181,
                parentId: 194,
                displayOrder: 4,
                type: "Text",
                item: "Messages",
                script: "message",
                condition: "Messages",
                description: "Messages",
                recordStatus: "Active",
                children: [
                    {
                        menuId: 159,
                        parentId: 181,
                        displayOrder: 2,
                        type: "Text",
                        item: "Translation",
                        script: "/modules/translation",
                        condition: "Show All",
                        description:
                            "This Menu will show all the translation available on the app",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 183,
                        parentId: 181,
                        displayOrder: 6,
                        type: "Text",
                        item: "Canned Message Key",
                        script: "/modules/cannedMessagekey",
                        condition: "Canned-Message-Key",
                        description: "Canned Message Key",
                        recordStatus: "Active",
                        children: [],
                    },
                    {
                        menuId: 182,
                        parentId: 181,
                        displayOrder: 7,
                        type: "Text",
                        item: "Canned Message Details",
                        script: "/modules/cannedMessage",
                        condition: "Canned Messages",
                        description: "Canned Messages",
                        recordStatus: "Active",
                        children: [],
                    },
                ],
            },
            {
                menuId: 175,
                parentId: 194,
                displayOrder: 5,
                type: "Text",
                item: "Bus Carriers",
                script: "/modules/bus-carriers",
                condition: "none",
                description: "Bus Carriers",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 176,
                parentId: 194,
                displayOrder: 6,
                type: "Text",
                item: "Bus Locations",
                script: "/modules/bus_locations",
                condition: "Admin-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
        ],
    },
    {
        menuId: 195,
        parentId: 0,
        displayOrder: 6,
        type: "Text",
        item: "SUPPLIERS",
        script: "suppliers",
        condition: "none",
        description: null,
        recordStatus: "Active",
        children: [
            {
                menuId: 199,
                parentId: 195,
                displayOrder: 1,
                type: "Text",
                item: "Supplier",
                script: "/modules/supplier",
                condition: "Suppliers",
                description: "abcdefghijklmnopqrstuvwxyz",
                recordStatus: "Undeleted",
                children: [],
            },
            {
                menuId: 173,
                parentId: 195,
                displayOrder: 2,
                type: "Text",
                item: "Airline Policies",
                script: "/modules/airline_policies",
                condition: "None",
                description: "Airline Policies",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 190,
                parentId: 195,
                displayOrder: 3,
                type: "Text",
                item: "Malpractice Limits",
                script: "/modules/malpractice",
                condition: "Admin-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 28,
                parentId: 195,
                displayOrder: 4,
                type: "Text",
                item: "Menu",
                script: "/modules/menu",
                condition: "Chilld1-condition",
                description: "Menu",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 32,
                parentId: 195,
                displayOrder: 5,
                type: "Text",
                item: "Scope",
                script: "/modules/scope",
                condition: "management-scope",
                description: "scope menu",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 167,
                parentId: 195,
                displayOrder: 6,
                type: "Text",
                item: "Airlines",
                script: "/modules/airline",
                condition: "Admin-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 166,
                parentId: 195,
                displayOrder: 7,
                type: "Text",
                item: "Airline Classes",
                script: "/modules/airline_class",
                condition: "None",
                description: "Airline Classes",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 171,
                parentId: 195,
                displayOrder: 8,
                type: "Text",
                item: "Flight Alliances",
                script: "/modules/flight_alliances",
                condition: "admin-flight-alliances",
                description: null,
                recordStatus: "Active",
                children: [],
            },
        ],
    },
    {
        menuId: 196,
        parentId: 0,
        displayOrder: 7,
        type: "Text",
        item: "GLOBAL",
        script: "global",
        condition: "none",
        description: null,
        recordStatus: "Active",
        children: [
            {
                menuId: 172,
                parentId: 196,
                displayOrder: 13,
                type: "Text",
                item: "Loyality Cards",
                script: "/modules/loyalty_cards",
                condition: "admin-loyality-cards",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 187,
                parentId: 196,
                displayOrder: 14,
                type: "Text",
                item: "Credit Cards",
                script: "/modules/creditCard",
                condition: "Credit-cards",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 193,
                parentId: 196,
                displayOrder: 17,
                type: "Text",
                item: "Countries",
                script: "/modules/countries",
                condition: "None",
                description: "Countries Info",
                recordStatus: "Active",
                children: [],
            },
        ],
    },
    {
        menuId: 197,
        parentId: 0,
        displayOrder: 8,
        type: "Text",
        item: "CUSTOMER",
        script: "company",
        condition: "none",
        description: null,
        recordStatus: "Active",
        children: [
            {
                menuId: 169,
                parentId: 197,
                displayOrder: 1,
                type: "Text",
                item: "Cost Centers",
                script: "/modules/cost_centers",
                condition: "0",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 177,
                parentId: 197,
                displayOrder: 2,
                type: "Text",
                item: "Company Group",
                script: "/modules/company_group",
                condition: "None",
                description: "Company Group",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 179,
                parentId: 197,
                displayOrder: 3,
                type: "Text",
                item: "Company Groups Member",
                script: "/modules/company_groups_member",
                condition: "None",
                description: "Company Groups Member",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 178,
                parentId: 197,
                displayOrder: 4,
                type: "Text",
                item: "Branches",
                script: "/modules/branches",
                condition: "None",
                description: "branches",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 185,
                parentId: 197,
                displayOrder: 5,
                type: "Text",
                item: "Orders",
                script: "/modules/orders",
                condition: "Admin-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 188,
                parentId: 197,
                displayOrder: 6,
                type: "Text",
                item: "Travel Reason",
                script: "/modules/travelReason",
                condition: "None",
                description: "Travel Reason",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 189,
                parentId: 197,
                displayOrder: 7,
                type: "Text",
                item: "Expense Type",
                script: "/modules/expenseType",
                condition: "None",
                description: "Expense Type",
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 184,
                parentId: 197,
                displayOrder: 8,
                type: "Text",
                item: "Communications",
                script: "/modules/communications",
                condition: "Help-Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 205,
                parentId: 197,
                displayOrder: 11,
                type: "Text",
                item: "Carrier Messages",
                script: "/modules/carrierMessages",
                condition: "Customer",
                description: null,
                recordStatus: "Active",
                children: [],
            },
            {
                menuId: 207,
                parentId: 197,
                displayOrder: 13,
                type: "Text",
                item: "Fare Messages",
                script: "/modules/fareMessages",
                condition: "Condition",
                description: null,
                recordStatus: "Active",
                children: [],
            },
        ],
    },
];